name = "FLOWVPM"
uuid = "6e19019d-7c31-4940-9d16-c3f15dfe6020"
authors = ["Eduardo J. Alvarez <Edo.AlvarezR@gmail.com>"]
version = "0.1.0"

[deps]
FLOWExaFMM = "a07d1f4e-0e34-4d8b-bfef-e5b961477d34"

[compat]
julia = "1.4"
